#swagger:
#  base-package: com.mayikt.member.service.api.impl
#  title: SpringCloud2.x构建微服务电商项目-会员服务接口
#  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由每特教育|蚂蚁课堂版权所有，未经过允许的情况下，私自分享视频和源码属于违法行为。
#  version: 1.1
#  terms-of-service-url: www.mayikt.com
#  contact:
#    name: 97后互联网架构师-余胜军
#    email: 644064779@qq.com
#    url: www.mayikt.com
#  enabled: true
#
#spring:
#  ###数据库相关连接
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.106.190.68:3306/mayikt_member?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 729754701
#
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 729754701
#    pool:
#      max-idle: 100
#      min-idle: 1
#      max-active: 1000
#      max-wait: -1
#  main:
#    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#
#mayikt:
#  login:
#    token:
#      channel: pc,android,ios
#    qq:
#      accesstoken: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id={client_id}&client_secret={client_secret}&code={code}&redirect_uri={redirect_uri}
#      openid: https://graph.qq.com/oauth2.0/me?access_token=
#    wx:
#      accesstoken: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
